steps:
  - id: 'deploy-and-execute-job'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - '${_JOB_NAME}'
      - '--source'
      - '.'
      - '--region'
      - '${_REGION}'
      - '--execute-now'

substitutions:
  _REGION: 'asia-northeast1'
  _JOB_NAME: 'python-executor-job'

options:
  logging: CLOUD_LOGGING_ONLY
